# Spring Boot Configuration
spring.application.name=conflict-tracker

# Database Configuration
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://db.nsghtrmtwtfldyernjvb.supabase.co:5432/postgres}
spring.datasource.driverClassName=${DB_DRIVER:org.postgresql.Driver}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}

# JPA Configuration
spring.jpa.database-platform=${JPA_DIALECT:org.hibernate.dialect.PostgreSQL10Dialect}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:create}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Configuration
spring.jpa.properties.hibernate.jdbc.batch_size=10
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Server Configuration
server.port=${PORT:8080}